filname=input("enter the file name(myfile.txt)")
file1=open(filname,'w')
file1.write("hello good morning this  morning is beautiful  ")
file1.close()
file1=open(filname,"r")
f=file1.read()
print(len(f.split()),"no of words")
print(len(f),"no of characters")
print(len(f.split('\n')),"no of line")
file1.close()
